import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { LinkType } from "@/types";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
const links: LinkType[] = [
	{ name: "Home", path: "/" },
	{ name: "Converters", path: "/converters" },
];

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}>
				<div className="min-h-screen flex flex-col bg-gradient-to-br from-frutigerPaleBlue via-frutigerPaleGreen to-frutigerPaleOrange  font-sofia font-sans">
					<Navbar links={links} />
					{children}
					<footer className="absolute bottom-0 z-10 left-0 right-0 text-center text-xs sm:text-base py-4 bg-transparent text-slate-400 w-full">
						© 2025{" "}
						<a href="https://alextendjer.com" className="underline">
							Aleksandar Tendjer
						</a>
						. All rights reserved.
					</footer>
				</div>
			</body>
		</html>
	);
}
